#pragma once

#include "System/Type.h"

#include "UnityEngine/Object.h"
#include "UnityEngine/Component.h"
#include "UnityEngine/Behaviour.h"
#include "UnityEngine/MonoBehaviour.h"
#include "UnityEngine/GameObject.h"
#include "UnityEngine/Transform.h"
#include "UnityEngine/Shader.h"
#include "UnityEngine/Material.h"
#include "UnityEngine/Renderer.h"
#include "UnityEngine/Time.h"
#include "UnityEngine/Text.h"
#include "UnityEngine/Camera.h"
#include "UnityEngine/Physics.h"
#include "UnityEngine/Canvas.h"
#include "UnityEngine/Image.h"
#include "UnityEngine/Button.h"
#include "UnityEngine/SkinnedMeshRenderer.h"

#include "System/Array.h"
#include "System/Dictionary.h"
#include "System/Uri.h"
#include "System/FakeDictionary.h"
#include "System/List.h"

#include "RecRoom/ObscuredTypes.h"

#include "Photon/Hashtable.h"
#include "Photon/PhotonPlayer.h"
#include "Photon/PhotonView.h"
#include "Photon/MonoBehaviourPun.h"
#include "Photon/LoadBalancingClient.h"

#include "RecRoom/PlayerHand.h"
#include "RecRoom/Player.h"
#include "RecRoom/RecRoomSceneManager.h"
#include "RecRoom/PlayerGameRoleManager.h"
#include "RecRoom/RangedWeapon.h"
#include "RecRoom/CreationObject.h"
#include "RecRoom/CircuitsV2Manager.h"
#include "RecRoom/GiftPackage.h"
#include "RecRoom/GiftManager.h"
#include "RecRoom/PlayerAvatarDisplay.h"
#include "RecRoom/QuestManager.h"
#include "RecRoom/BaseAccountModel.h"
#include "RecRoom/AccessToken.h"
#include "RecRoom/ShareCamera.h"
#include "RecRoom/AudioPlayer.h"
#include "RecRoom/MultiPlayerEditableText.h"
#include "RecRoom/UGCSeatManagementProxy.h"

#include "Photon/EventData.h"
#include "Photon/PhotonNetwork.h"

#include "Dissonance/Dissonance.h"